import { ThemeConfig } from '@/components/ThemeConfig';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Cards Challenge',
    default: 'Cards Challenge',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeConfig>{children}</ThemeConfig>
      </body>
    </html>
  );
}
